ecam_my_project_homepage:
    path:     /
    defaults: { _controller: ECAMMyProjectBundle:Default:index }


# src/ECAM/MyProjectBundle/Resources/config/routing.yml
hello_the_world:
    path: /hello-world
    defaults: { _controller: ECAMMyProjectBundle:Default:index }



# src/ECAM/MyProjectBundle/Resources/config/routing.yml
ajouter:
    path: /ajouter
    defaults: { _controller: ECAMMyProjectBundle:note:index }

# src/ECAM/MyProjectBundle/Resources/config/routing.yml

hello_the_worlda:
    path: /hello-worlda
    defaults: { _controller: ECAMMyProjectBundle:Advert:index }



# src/OC/PlatformBundle/Resources/config/routing.yml

ecam_project_view_slug:
    path:      /platform/{year}/{slug}.{_format}
    defaults:
        _controller: ECAMMyProjectBundle:Advert:viewSlug
        format:      html
    requirements:
        year:   \d{4}
        format: html|xml


test2:
    path:      /platform/Advert/view2
    defaults:
        _controller: ECAMMyProjectBundle:Advert:view2



oc_platform_view:
    path:      /platform/Advert/{id}
    defaults:
        _controller: ECAMMyProjectBundle:Advert:index



# src/ECAM/MyProjectBundle/Resources/config/routing.yml

ecam_project_viewAdvert:
    path:      /Advert/view/{id}
    defaults:
        _controller: ECAMMyProjectBundle:Advert:view
    requirements:
        id: \d+


ecam_project_add:
    path:      /add
    defaults:
        _controller: ECAMMyProjectBundle:Advert:add

ecam_project_edit:
    path:      /edit/{id}
    defaults:
        _controller: ECAMMyProjectBundle:Advert:edit
    requirements:
        id: \d+

ecam_project_delete:
    path:      /delete/{id}
    defaults:
        _controller: ECAMMyProjectBundle:Advert:delete
    requirements:
        id: \d+
