<?php
/**
 * Created by PhpStorm.
 * User: Louis
 * Date: 25-03-17
 * Time: 14:12
 */

namespace ECAM\MyProjectBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
