<?php
/**
 * Created by PhpStorm.
 * User: Louis
 * Date: 25-03-17
 * Time: 14:16
 */


namespace ECAM\MyProjectBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
}
